yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from tokenize import group
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(verbose_name='URL')
    description = models.TextField()

    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True, 
        null=True,
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group
# Create your views here.
def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)

def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html> 
{% load static %}
<html lang="ru">          
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">      
  </head>
  <title>
    {% block title_head %}

    {% endblock %}
  </title>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<div class="container py-5">
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</div>  

yatube/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->    
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="/static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}

{% block title_head %}
  Здесь будет информация о группах проекта Yatube
  {% endblock %}

{% block content %}
<div class="container py-5">
  {% block title %}
    <h1>Лев Толстой – зеркало русской революции.</h1>
  {% endblock %}
  {% for post in posts %}
    <h3>
      {{ group.title }}
    </h3>
    <p>
      {{ group.description }}
    </p>
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d M Y" }}
        </li>
      <p>
        {{ post.text }}
      </p>
    </article>
  {% endfor %}
  </div>

{% endblock %}

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}

{% block title_head %}
  Главная страница
  {% endblock %}

{% block content %}
<div class="container py-5">
  {% block title %}
    <h1>Последние обнавление на сайте</h1>
  {% endblock %}
  
  <article>
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>
  {{ post.text }}
  </p>
  {% if post.group %}   
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы<hr></a>
  {% endif %}
  {% endfor %}
  </article>
</div>
{% endblock %}